# -*- coding: utf-8 -*-
"""Rulebook rules transcribed from Rulebook-V-1.0.pdf (SIEP E-Bike Challenge 2025)."""

RULES = [
    # ── A. Introduction ────────────────────────────────────────────────────────
    dict(id='a-001', section='Introduction', subsection='About Organizer', rule_code='A.1',
         title='About Organizer',
         description='Imperial Society of Innovative Engineers (ISIEINDIA) is the organizing body of the SIEP E-Bike Challenge.'),
    dict(id='a-002', section='Introduction', subsection='About Organizer', rule_code='A.1.1',
         title='Imperial Society of Innovative Engineers',
         description='Imperial Society of Innovative Engineers is the most popular and favourite E-mobility motorsports, education and research publication organization in India among engineering institutes and professionals.'),
    dict(id='a-003', section='Introduction', subsection='Event Accreditation', rule_code='A.2',
         title='Event Accreditation',
         description='The event is accredited in association with the Society of Manufacturers of Electric Vehicles (SMEV).'),
    dict(id='a-004', section='Introduction', subsection='Event Accreditation', rule_code='A.2.1',
         title='Society of Manufacturers of Electric Vehicles',
         description='SMEV works closely with the central and state governments to assist the formulation of policies and processes supporting the EV ecosystem.'),
    dict(id='a-005', section='Introduction', subsection='About SIEP', rule_code='A.3',
         title='About Skill Innovation & Employability Program',
         description='SIEP is a skill development program that runs in two classes: Retrofitting an existing internal-combustion bike, and Self-Manufactured class where a new electric motorbike is designed and built.'),
    dict(id='a-006', section='Introduction', subsection='About SIEP', rule_code='A.3.1',
         title='Overview',
         description='This event is entirely different from other events, where manufacturing of the vehicle and retrofitting are both included. It is entirely based on the innovation of drivetrain and other aspects, and integration of those innovations from the Virtual Round to the Final Round.'),
    dict(id='a-007', section='Introduction', subsection='About SIEP', rule_code='A.3.2',
         title='Objective',
         description='To skill the engineering students towards new and trending technologies through this innovative program, and to inculcate a culture of innovation and technology.'),
    dict(id='a-008', section='Introduction', subsection='About SIEP', rule_code='A.3.3',
         title='The Event will be in two classes',
         description='Retrofitting Class: a light weight, smooth and fast to ride vehicle providing an eco-friendly and economical cruising experience. Self-Manufactured Class: manufacture an electric motorbike which in future meets commercial requirements and promotes E-Mobility.'),

    # ── B. Administrative Rules ───────────────────────────────────────────────
    dict(id='b-001', section='Administrative', subsection='Participation Requirements', rule_code='B.1',
         title='Participation Requirements',
         description='By submitting an application, entrants declare that they know and understand the regulations of the event and agree that participation will constitute their full acceptance. The entrant is responsible for regulatory compliance, the actions of team members and any other individuals associated with the team.'),
    dict(id='b-002', section='Administrative', subsection='Participation Requirements', rule_code='B.1.1',
         title='Eligibility Criteria',
         description='Educational Qualification: Team members must be enrolled as degree-seeking undergraduate, graduate or diploma students in a college or university.'),
    dict(id='b-003', section='Administrative', subsection='Participation Requirements', rule_code='B.1.2',
         title='Qualification',
         description='Entrants who do not satisfy the Chief Scrutinizer that they will achieve compliance with the regulations through documentary submission may fail to qualify for the event and their place may be offered to a team on the waiting list.'),
    dict(id='b-004', section='Administrative', subsection='Participation Requirements', rule_code='B.1.3',
         title='Entrant Obligation',
         description='Entrants are expected to act fairly and in good faith in accordance with the regulations. Penalties, which may include exclusion, will be applied to any team deemed to have departed from the spirit of the event by deliberately acting to gain an unfair advantage over others, or by conduct that could bring the event into disrepute.'),
    dict(id='b-005', section='Administrative', subsection='Team Identification', rule_code='B.2',
         title='Team Identification Requirements',
         description='Design and fabrication of the vehicle should be done by the team. A meaningful and inspirational team name is required to distinguish the team in the competition.'),
    dict(id='b-006', section='Administrative', subsection='Team Identification', rule_code='B.2.1',
         title='Team Name',
         description='A meaningful and inspirational team name is required to distinguish the team in the competition.'),
    dict(id='b-007', section='Administrative', subsection='Team Identification', rule_code='B.2.2',
         title='Team Logo',
         description='An attractive team logo, not downloaded from the internet, is required from the participating team. Teams must use their team logo in reports, on their vehicle and in videos.'),
    dict(id='b-008', section='Administrative', subsection='Team Identification', rule_code='B.2.3',
         title='Team Members',
         description='In case the team is seeking help from an industrial professional or experienced person, then it should be purely for an advisory purpose.'),
    dict(id='b-009', section='Administrative', subsection='Team Identification', rule_code='B.2.4',
         title='Total Members',
         description='Participants should have at least one team advisor from their college, university or industry, whom they are representing. They can have a maximum of two team advisors. One faculty advisor must accompany the team in the final event.'),
    dict(id='b-010', section='Administrative', subsection='Team Identification', rule_code='B.2.5',
         title='Team Mail ID',
         description='A valid team email ID is required for all official communication from the organizer. Important information will be sent via email to the respective team email after registration.'),
    dict(id='b-011', section='Administrative', subsection='Team Identification', rule_code='B.2.6',
         title='Team Advisor',
         description='Participants should have at least one team advisor from their college, university or industry. They can have a maximum of two team advisors, and one faculty advisor must accompany the team in the final event.'),
    dict(id='b-012', section='Administrative', subsection='Driver', rule_code='B.3',
         title='Driver Requirements',
         description='Every team must have one driver. The driver must have their complete safety kit.'),
    dict(id='b-013', section='Administrative', subsection='Driver', rule_code='B.3.3',
         title='Driver Restriction',
         description='The driver must be from the team. Any professional driver from outside is not allowed to ride the vehicle during the competition. A team member who will drive a competition vehicle at any time during a competition must hold a valid driving licence.'),
    dict(id='b-014', section='Administrative', subsection='Driver', rule_code='B.3.4',
         title='Medical Insurance',
         description='Drivers must have individual medical and accidental insurance coverage. It is required and is the sole responsibility of the participant. A driver without a valid medical insurance will not be permitted to drive in the dynamic events.'),
    dict(id='b-015', section='Administrative', subsection='Driver', rule_code='B.3.5',
         title='Age',
         description='The driver must satisfy the age criteria declared in the event registration form and must carry valid proof of age during the technical inspection.'),
    dict(id='b-016', section='Administrative', subsection='Vehicle Eligibility', rule_code='B.4',
         title='Vehicle Eligibility',
         description='Vehicles entering for SIEP must be conceived, designed, fabricated and maintained by the team members.'),
    dict(id='b-017', section='Administrative', subsection='Vehicle Eligibility', rule_code='B.4.1',
         title='Student Developed Vehicle',
         description='Vehicles entering for SIEP must be conceived, designed, fabricated and maintained by the team members without direct involvement from professional engineers, automotive engineers, racers, machinists or related professionals.'),
    dict(id='b-018', section='Administrative', subsection='Vehicle Eligibility', rule_code='B.4.2',
         title='Entries per University',
         description='Multiple teams from the same university or engineering college can participate in the event.'),
    dict(id='b-019', section='Administrative', subsection='Registration Process', rule_code='B.5',
         title='Registration Process',
         description='Applications may be made from the time these regulations are published until such other time as the event organizer may determine. Applications for entry must be made via the official online entry form.'),
    dict(id='b-020', section='Administrative', subsection='Registration Process', rule_code='B.5.1',
         title='Entering the Event Process',
         description='Applications for entry must be made via the official online entry form available at www.imperialsociety.in/siep. Entry requests will only be considered on payment of the application fee. The number of places is limited and applications received after the limit is reached may be placed on a waiting list. The registration will become void if the entry fees have not been received by the due date.'),
    dict(id='b-021', section='Administrative', subsection='Registration Process', rule_code='B.5.2',
         title='Registration Process Guidelines',
         description='Sign up or log in at https://igms.imperialsociety.in/login, click to register for the event, select the event name and complete the required details of the event form. Once the team has been registered, they are required to submit their fees within 3 working days. Team members including the captain must have an ISIE Student/Professional membership.'),
    dict(id='b-022', section='Administrative', subsection='Registration Process', rule_code='B.5.3',
         title='Access Team Account / Add or Remove Members',
         description='Log in to your team account at https://igms.imperialsociety.in/login. Your registered event will be automatically visible to you on login. Add details of the team members. In case of any change to team leader, faculty advisor or team name, an application with the details must be sent to the organizer.'),
    dict(id='b-023', section='Administrative', subsection='Registration Process', rule_code='B.5.4',
         title='Registration Form',
         description='After online registration and payment confirmation, a copy of the registration form attested by a higher authority of the team\'s respective university, college, industry or organization must be submitted on the online submission portal.'),
    dict(id='b-024', section='Administrative', subsection='Registration Process', rule_code='B.5.5',
         title='Registration Fees',
         description='Registration fees must be paid to the ISIEINDIA by or before the deadlines, within 3 working days after the registration.'),
    dict(id='b-025', section='Administrative', subsection='Registration Process', rule_code='B.5.6',
         title='Mode of Payment',
         description='Demand draft in favour of Imperial Society of Innovative Engineers, payable at ICICI Bank.'),
    dict(id='b-026', section='Administrative', subsection='Registration Process', rule_code='B.5.7',
         title='Registration Fees Confirmation',
         description='If the payment is followed by a bank holiday, then confirmation will be done after 48 hours.'),
    dict(id='b-027', section='Administrative', subsection='Registration Process', rule_code='B.5.8',
         title='Registration Fee Deadline and Refund',
         description='Registration fees must be paid to the ISIEINDIA by or before the deadlines, within 3 working days after registration. Registration fees are non-refundable and will not be transferred to any subsequent year\'s competition.'),
    dict(id='b-028', section='Administrative', subsection='Registration Process', rule_code='B.5.9',
         title='Withdrawals',
         description='Registered teams that find that they will not be able to attend the competition are required to officially withdraw by mail to ebike.siep@imperialsociety.in no later than 4 weeks before the event. Registration fees are NOT refundable and non-transferable.'),
    dict(id='b-029', section='Administrative', subsection='Registration Process', rule_code='B.5.10',
         title='Cancellation of the Event',
         description='The event organizer reserves the right to cancel or abandon the event for any reason.'),
    dict(id='b-030', section='Administrative', subsection='Compulsory Documentation', rule_code='B.6',
         title='Compulsory Documentation',
         description='Each team must submit documentation using the online forms. All submissions must be made by the dates stated in the event schedule.'),
    dict(id='b-031', section='Administrative', subsection='Compulsory Documentation', rule_code='B.6.1',
         title='Group A & ESF-I Documentation',
         description='Design Specification Sheet, Design Report, Electrical System Form ESF-I, Gantt Chart, DFMEA Report.'),
    dict(id='b-032', section='Administrative', subsection='Compulsory Documentation', rule_code='B.6.2',
         title='Group B Documentation',
         description='Motor Performance, Battery Performance, Vehicle Health Monitoring System, Speed Limited Based on Modes, Driverless Parking Assistance, Self-Balancing, Cost Report, Electrical System Form ESF-II.'),
    dict(id='b-033', section='Administrative', subsection='Compulsory Documentation', rule_code='B.6.3',
         title='Group C Documentation',
         description='Logistics schedule, travel, arrival and accommodation information.'),
    dict(id='b-034', section='Administrative', subsection='Compulsory Documentation', rule_code='B.6.4',
         title='Video Submission',
         description='The video must have clips showing different stages of fabrication of the vehicle and testing of the vehicle: team introduction, designing of the bike using software, chassis manufacturing (cutting, grinding and welding), mounting of all parts, and testing of the vehicle. Any scene should not continue for more than 5-6 seconds. Videography must be clear. Use a good quality camera and add the relevant part only. The video must not be more than 250 MB. During manufacturing, use proper safety equipment like gloves and goggles. During testing, the driver must be in proper safety gear. Testing of the vehicle should be done in day time.'),
    dict(id='b-035', section='Administrative', subsection='Compulsory Documentation', rule_code='B.6.5',
         title='College / University Level Technical Submission',
         description='The format of the college level technical inspection sheet will be provided by the E-Bike Challenge organizer. Teams are required to submit only a soft copy of the T.I. sheet as per the given guidelines.'),

    # ── C. Technical Rules ─────────────────────────────────────────────────────
    dict(id='c-001', section='Technical', subsection='Vehicle Types', rule_code='C.1',
         title='Vehicle Types',
         description='The event runs in two classes: Retrofitting Class and Self-Manufactured Class.'),
    dict(id='c-002', section='Technical', subsection='Vehicle Types', rule_code='C.1.1',
         title='Retrofitting Class',
         description='The purpose of this segment of a retrofitted bike is to provide immense riding pleasure to the users without changing the bike essence. A light weight, smooth and fast to ride vehicle of this class should provide an ultimate eco-friendly and economical cruising experience to end users.'),
    dict(id='c-003', section='Technical', subsection='Vehicle Types', rule_code='C.1.2',
         title='Self-Manufactured Class',
         description='The purpose of this segment is to manufacture an electric motorbike which in future meets the commercial requirements and promotes E-Mobility among the society.'),
    dict(id='c-004', section='Technical', subsection='Design Restriction', rule_code='C.2',
         title='Design Restriction',
         description='Overall design restrictions apply to dimensions, wheels sizing and the paddock stand.'),
    dict(id='c-005', section='Technical', subsection='Design Restriction', rule_code='C.2.1',
         title='Dimensions — Retrofitting Class',
         description='It is mandatory to keep the dimensions of the bike the same as they were before retrofitting. The battery pack, motor and any other innovative additions should not change the length, width and height of the bike. Maximum width of the bike will be measured from end to end points of the handle. All parts of the bike including the driver should lie within the end to end points of the handle. The maximum weight of the retrofitted bike must not exceed 150 kg. Bodyworks can be of any material and ensure good aesthetics. You need to remove the fuel tank and use your own bodyworks which cover the battery pack and other components. Available fuel tank casing is not allowed; it should be replaced with bodyworks.'),
    dict(id='c-006', section='Technical', subsection='Design Restriction', rule_code='C.2.1.2',
         title='Dimensions — Self-Manufactured Class',
         description='The wheelbase of the bike should be in the range of 48 inches to 62 inches. The minimum ground clearance should be 5 inches. The maximum length should not exceed more than 80 inches. The maximum width of the bike should not be more than 40 inches. The maximum height of the bike without rider should not be more than 60 inches. No points will be awarded if the weight of the bike is more than 150 kg. Bodyworks can be of any material and ensure good aesthetics; soft plastic is not allowed.'),
    dict(id='c-007', section='Technical', subsection='Design Restriction', rule_code='C.2.2',
         title='Wheels Sizing',
         description='The minimum diameter of the tires should be 16 inches. Teams are allowed to use alloy wheels as well as spoke rims. The maximum allowed tire width is 7 inches. Bicycle tires are prohibited. Moto GP slick tires are prohibited.'),
    dict(id='c-008', section='Technical', subsection='Design Restriction', rule_code='C.2.3',
         title='Paddock Stand',
         description='It is compulsory to have a paddock stand for both classes. It is compulsory to have a side stand for both classes. Main stand is prohibited. Maximum height of the paddock stand should be 78 cm. Maximum length of the paddock stand should be 50 cm. Maximum width of the paddock stand should be 54 cm.'),
    dict(id='c-009', section='Technical', subsection='Chassis Restrictions', rule_code='C.3',
         title='Chassis Restrictions',
         description='Chassis cross-section, material specification, ergonomics, frame dimensions, gyroscopic effect, bike seat and mudguards are all regulated.'),
    dict(id='c-010', section='Technical', subsection='Chassis Restrictions', rule_code='C.3.1',
         title='Chassis Cross Section',
         description='Retrofitting class: teams are instructed to use the same frame as availed from the bike. All welding points in the frame should be intact and damaged frames will be disqualified on spot. The frame will be strictly inspected in the technical inspection. Self-Manufactured class: teams should manufacture a double cradle frame only, consisting of two main pipes. Seamless tubes are required; seamed tubes are strictly not allowed. Minimum wall thickness must be 1 mm. One end of the chassis must be open to check the material.'),
    dict(id='c-011', section='Technical', subsection='Chassis Restrictions', rule_code='C.3.2',
         title='Material Specification',
         description='Steel, aluminum or carbon fibre. In the case of steel, the minimum carbon percentage should be 0.1%. Material composition and strength test certificate from a certified laboratory only (NABL accredited lab) is required.'),
    dict(id='c-012', section='Technical', subsection='Chassis Restrictions', rule_code='C.3.3',
         title='Ergonomics',
         description='The frame should be designed so that it is comfortable and safe for the rider over the duration of the event.'),
    dict(id='c-013', section='Technical', subsection='Chassis Restrictions', rule_code='C.3.4',
         title='Dimension of Frame',
         description='The frame dimensions must be consistent with the overall vehicle dimensions specified in C.2.1 and must not exceed the permitted length, width and height.'),
    dict(id='c-014', section='Technical', subsection='Chassis Restrictions', rule_code='C.3.5',
         title='Gyroscope',
         description='Teams must manufacture their frame keeping in mind the gyroscopic effect of the bike. Balancing the bike should be easy and should be ergonomically comfortable to the rider.'),
    dict(id='c-015', section='Technical', subsection='Chassis Restrictions', rule_code='C.3.6',
         title='Bike Seat',
         description='Self-Manufactured class must use a pre-manufactured seat and its mounting should be according to the seat. Retrofitting class must use the same seat. In case the seat is damaged in the Retrofitting class they can alter the seat but it should be of the same bike.'),
    dict(id='c-016', section='Technical', subsection='Chassis Restrictions', rule_code='C.3.7',
         title='Mudguards',
         description='The use of front and rear mudguards is compulsory.'),
    dict(id='c-017', section='Technical', subsection='Suspension System', rule_code='C.4',
         title='Suspension System',
         description='Suspension constraints apply to both the retrofitted and self-manufactured classes.'),
    dict(id='c-018', section='Technical', subsection='Suspension System', rule_code='C.4.1',
         title='Suspension Constraints — Retrofitting Class',
         description='Teams are allowed to use the same suspension system of the bike. The mounting of the front suspension should be done according to the rake/caster angle of the bike. Teams are allowed to use either mono-shock or twin shock suspension at the rear as acquired from the already purchased bike. If any team wishes to change the front or the rear or both suspensions, they must mention the same in the design report, which will include the suspension design, CAD model, dynamic simulations and how it differs from the bike\'s original system.'),
    dict(id='c-019', section='Technical', subsection='Suspension System', rule_code='C.4.1.2',
         title='Suspension Constraints — Self-Manufactured Class',
         description='Teams are allowed to use a pre-fabricated suspension system of any bike at the front as well as at the rear. The mounting of the front suspension should be done according to the rake/caster angle of the bike. Teams can customize both the suspension system. Teams are allowed to use either mono-shock or twin shock suspension at the rear. If teams customize the suspension system, they have to submit an entire suspension design report and all calculations including the CAD model and dynamic simulations.'),
    dict(id='c-020', section='Technical', subsection='Suspension System', rule_code='C.4.1.3',
         title='Suspension Constraints — General (Both Classes)',
         description='Teams should calculate spring or damping lag on both the suspension systems. Teams have to calculate squat and dive occurring on the bike. Teams should have the calculation of the spring rate.'),
    dict(id='c-021', section='Technical', subsection='Steering System', rule_code='C.5',
         title='Steering System',
         description='Steering constraints apply to both classes.'),
    dict(id='c-022', section='Technical', subsection='Steering System', rule_code='C.5.1',
         title='Steering Constraints',
         description='Teams are allowed to use a pre-fabricated bike handle in both the classes. Teams can modify the handle according to their requirements in both the classes, but they must mention the modification in detail in the design report including its methodology. The turning angle must be limited with stoppers on both sides. These stoppers should be made of nylon, aluminum or materials of similar hardness. Neither the chassis, nor any other part of the prototype may act as a steering stopper. The minimum turning angle of the steering must be 150 degrees measured on either side of the longitudinal axis of the prototype. The allowed rake angle is 22 to 32 degrees. Steering axis inclination should have offset with the front wheel center. The steering system must have positive steering stops that prevent the steering linkages from locking up.'),
    dict(id='c-023', section='Technical', subsection='Braking System', rule_code='C.6',
         title='Braking System',
         description='The bike must be equipped with brakes on both the wheels, operated by a different control.'),
    dict(id='c-024', section='Technical', subsection='Braking System', rule_code='C.6.1',
         title='Braking Constraints',
         description='Retrofitting class bikes can use a mechanical or a hydraulic or a combination of both braking systems. Self-manufactured class bikes must use a hydraulic braking system.'),
    dict(id='c-025', section='Technical', subsection='Braking System', rule_code='C.6.2',
         title='Brake Types',
         description='It must have two independent hydraulic circuits such that in the case of a leak or a failure at any point, effective braking power is maintained on at least one of the wheels. Each hydraulic circuit must have its own fluid reserve. For the Self-Manufactured class, brake-by-wire or mechanical systems are prohibited. The front and the rear must have different disc diameters for both classes. Teams should calculate the heat dissipation, braking torque and braking force in newton as well as with respect to g-force. Ventilated discs are prohibited. Front brake pedal should be of lever type and hand operated. Rear brake pedal should be mounted near the foot rest and foot operated. Loose mounted brake levers and pedals are strictly prohibited. The brake system must be capable of locking the wheels during the brake test and the bike should not yaw more than 30 degrees while braking. Retrofitting class can use drum or disc, or both in combination, at the front and rear. It is mandatory to use only disc brakes at the front and the rear for the Self-Manufactured class.'),
    dict(id='c-026', section='Technical', subsection='Braking System', rule_code='C.6.3',
         title='Brake Light',
         description='The bike must have red colored brake lights at the rear. The brake light should be visible from a distance of 30 m. LED light strips are not allowed to be used as a brake light. The brake light must be clearly visible from the rear even in broad daylight and should function even when the motor is killed off. The brake light must glow continuously when brakes are applied.'),
    dict(id='c-027', section='Technical', subsection='Bike Dashboard', rule_code='C.7',
         title='Bike Dashboard',
         description='Team must install at least a standard dashboard on the vehicle. The dashboard must be behind the vertical plane drawn from the head light. If a team installs a smart dashboard, an extra 50 points will be added to the final results, and the working of the same has to be shown to the technical inspector.'),
    dict(id='c-028', section='Technical', subsection='Bike Dashboard', rule_code='C.7.1',
         title='Standard Dashboard',
         description='Team must have at least a standard dashboard on the vehicle. The dashboard should display readings of the speed, battery level indicator in % or bar, battery temperature, turn indicators, and high beam and low beam headlight indicators. The dashboard must not exceed beyond the headlight. Maximum dimensions of the dashboard: length 10 inch, width 7 inch. The dashboard should be fixed and have protective covering from dust and water. It should be visible and easily accessible to the rider, and should be rigidly mounted.'),
    dict(id='c-029', section='Technical', subsection='Bike Dashboard', rule_code='C.7.2',
         title='Smart Dashboard',
         description='Teams can modify the dashboard. The smart dashboard should display readings of the speed, battery level indicator in % or bar, battery temperature, turn indicators, high beam and low beam headlight indicators and a smoke detection indicator. Teams are allowed to use a tablet, mobile or any other digital integrated dashboard in the bike. The dashboard should be connected to an external device (mobile/tablet/laptop) through an application. The dashboard must not exceed beyond the headlight. Maximum dimensions: length 10 inch, width 7 inch. It should be fixed, have protective covering from dust and water, be visible and accessible to the rider, and be rigidly mounted. The team must show the actual performance of the health monitoring system.'),
    dict(id='c-030', section='Technical', subsection='Speed Limiter', rule_code='C.8',
         title='Speed Limiter Based on Modes',
         description='It is mandatory to install a speed limiter based on modes. Teams are required to run their vehicle in different modes and select the modes, then accelerate to the extreme end. While accelerating at the extreme end, the power must not go beyond the max power limit. The speed of the vehicle at each mode should be visible on the dashboard, and the mode of the vehicle should be shown on the dashboard. Teams are required to show the actual performance of the speed limiter system and check the practical performance of the vehicle.'),
    dict(id='c-031', section='Technical', subsection='Innovations (Optional)', rule_code='C.9',
         title='Innovations (Optional)',
         description='The following innovations are optional to install on the bike. Teams can add more innovations than those mentioned and present them in the innovation round. Extra 50 points will be awarded for both the innovations.'),
    dict(id='c-032', section='Technical', subsection='Innovations (Optional)', rule_code='C.9.1',
         title='Self-Balancing',
         description='Teams are required to prepare a self-balanced vehicle. Teams are required to make a bike in such a way that the rider must complete the track without using their legs for balancing the vehicle. The bike must not topple over before completing the circuit, and after completing the track it should be in a standstill condition without any support. During the whole round teams are not allowed to use any side stand, paddock stand, legs or any other support to balance the vehicle.'),
    dict(id='c-033', section='Technical', subsection='Innovations (Optional)', rule_code='C.9.2',
         title='Driverless Parking Assistance',
         description='Teams must work on driverless parking assistance. It can be operated either voice-activated or remote controlled. Teams need to park the vehicle through voice or remote control. A narrow patch will be provided to park the vehicle. The use of side and paddock stands during this round is prohibited. An emergency shutdown system should be installed on the remote or app so as to stop the vehicle in an emergency. Students should have knowledge about intelligent systems for parking space measurement and calculation of optimal steering maneuvers. In this round, the vehicle should be driverless operated.'),
    dict(id='c-034', section='Technical', subsection='Electrical Systems', rule_code='C.10',
         title='Electrical Systems',
         description='Definitions, battery, BMS, battery casing, battery position, charging and swapping, battery safety, level indicator, motor, motor controller and drive train.'),
    dict(id='c-035', section='Technical', subsection='Electrical Systems', rule_code='C.10.1',
         title='Definitions and General Aspects',
         description='High Voltage System: any circuit with a potential difference above 40 VDC will be part of the high voltage (HV) system of the bike. Below this voltage it is considered part of the low voltage (LV) system. The maximum permitted voltage of the HV system shall be 72 VDC. The use of software elements to control the maximum voltage is allowed. HV cables must be shielded. The HVS must be electrically separated from the bike chassis or ground. There must be high voltage labels such as "HIGH VOLTAGE". The HVS must have a controller device fitted in between the motor and the battery. The dashboard must be fitted with a display showing the voltage between terminals in the HVS at any given time. All components of the HVS must be located inside a reinforced structure that ensures their integrity in case of a crash.'),
    dict(id='c-036', section='Technical', subsection='Electrical Systems', rule_code='C.10.1.2',
         title='Ground Low Voltage System (GLVS)',
         description='The ground low voltage system is made up of any circuit or electrical part of the bike chassis and hence is not part of the HVS. The GLVS must be an LV system with a voltage below 40 VDC.'),
    dict(id='c-037', section='Technical', subsection='Electrical Systems', rule_code='C.10.1.3',
         title='Insulation and Cabling',
         description='The HVS and the GLVS shall be galvanically separated. All components of the HVS must be duly insulated and protected against direct contact. The HVS connections must be encapsulated in insulating components. The cables or conductors pertaining to the HVS must be orange, or clearly marked with orange, and non-flammable grade UL-94 V0, FAR 25 or equivalent.'),
    dict(id='c-038', section='Technical', subsection='Electrical Systems', rule_code='C.10.2',
         title='Battery Specification',
         description='Teams are allowed to use Li-Ion batteries only, e.g. Li-S / Li-ion / Li-polymer / LiFePO4. The team will not be allowed to change the battery pack; the same battery pack must be used throughout the event. Teams are allowed to use a pre-manufactured battery pack available in the market; a self-manufactured or assembled battery pack must provide the IP67 certificate and battery health certificate at the time of technical inspection from an authorized certifying agency. The battery pack should be IEC 60529 IP67 certified and must meet all weather conditions. If a team is using an old battery pack, a battery health certificate must be submitted. Allowed nominal voltage: 48 V to 72 V. Minimum energy 1.5 kWh, maximum energy 2.5 kWh.'),
    dict(id='c-039', section='Technical', subsection='Electrical Systems', rule_code='C.10.3',
         title='Battery Management System (BMS)',
         description='The installation of a battery management system is compulsory. The BMS must provide full cell protection to cover almost any eventuality and must read the voltage of each cell in order to keep the cells within the voltage limits established by the manufacturer. The BMS must deactivate the vehicle traction if the voltage of one of the cells is discharged to the critical minimum voltage, or if the critical maximum temperature of the cell is exceeded. The BMS must provide over-charge and over-discharge protection while charging and discharging, over-current protection, over-temperature and under-temperature protection, short circuit protection, reverse polarity protection and cell balancing functions. The BMS must also deactivate the recharge system when the maximum voltage or temperature levels of the cell are reached. Operating a battery outside its specified design limits of the BMS will lead to disqualification. Proper approval certifications should be presented during the technical inspection.'),
    dict(id='c-040', section='Technical', subsection='Electrical Systems', rule_code='C.10.4',
         title='Battery Casing',
         description='There should be a separate battery pack container and battery pack casing enclosures. The battery pack casing should be made of rigid plastic, glass fiber or sheet metal, with an insulating coating. The cover material of the battery pack must be fire and electric proof and properly insulated. Flexible rubber or plastic sheets are not allowed to be used as covers. The battery pack container should be fixed, welded or fastened using lock nuts with the chassis. Teams may use a forced convection system such that air from the atmosphere is forced into the battery pack container for cooling purposes. Liquid cooling of the battery pack is prohibited. Note: the battery pack with casing must be installed inside the battery pack container for easy removal.'),
    dict(id='c-041', section='Technical', subsection='Electrical Systems', rule_code='C.10.5',
         title='Battery Position',
         description='Self-Manufactured class: the battery must be placed as shown in the figure and inserted from the top. Zip tags are prohibited; use the wire coverings and attach them along the frame. It should be mounted rigidly, and nylon ties, strings or wires of any kind are not allowed for mounting. Retrofitting class: teams need not remove the backbone of the frame, as it might affect the gyroscopic feature of the bike. Teams can place the battery below the existing battery, just above or adjacent to the motor.'),
    dict(id='c-042', section='Technical', subsection='Electrical Systems', rule_code='C.10.6',
         title='Battery Charging Mount and Swapping',
         description='Teams must have a single point accessible charging point on the bike for charging the batteries at either side of the bike. Teams should have a charging connector for charging the batteries as per the charger specifications. Teams need to submit the datasheet for the charger and charging connector at the time of technical inspection. The battery pack must be mounted such that it can be swapped at any time from the top in the Self-Manufactured class and from the side in the Retrofit class. The battery swapping area must be indicated using stickers near the swapping area, with a yellow sticker. Battery swapping should be clean and safe with easy removal of the battery from the battery container.'),
    dict(id='c-043', section='Technical', subsection='Electrical Systems', rule_code='C.10.7',
         title='Battery Safety',
         description='Teams must understand the IP and AIS standards and their significance. If the power storage pack is capable of spilling dangerous liquids when damaged, there must be a spill-proof barrier between that storage pack and the bike occupants. If the pack can emit dangerous gases when damaged, there must be a proper ventilation system designed. The battery pack must have proper short circuit protection; teams should use good quality working mini circuit breakers (MCB) for protecting it from high loads. The current rating of the MCB should be equal to or greater than the motor controller rating. All safety devices like the brake light, indicator lights and horn should be powered either by the auxiliary battery (12 V) or a DC-DC converter. None of the battery parts or wires should be exposed to any body part of the rider. Teams must submit the ESF electrical system forms with all technical specification details for the motor, controller and battery charger, along with supporting certification documents, for SIEP approval.'),
    dict(id='c-044', section='Technical', subsection='Electrical Systems', rule_code='C.10.8',
         title='Battery Level Indicator',
         description='The battery pack must contain a temperature sensor whose reading must be accurately indicated on the dashboard. The battery pack may contain a smoke sensor whose reading must be accurately indicated on the dashboard. A battery level indicator must be provided in front of the rider on the dashboard. Teams must be able to monitor it during the event; it should display the percentage or bar of the battery based on the voltage or current of the battery pack for the full duration of the event.'),
    dict(id='c-045', section='Technical', subsection='Electrical Systems', rule_code='C.10.9',
         title='Motor',
         description='Teams are allowed to use any type of motor, AC or DC, and it should vary from 1250 W to 2000 W rated power. The motor must be manufactured as per IEC 60529 IP67; teams are required to submit the certificate from their vendor. The power rating of the motor will be strictly inspected in the technical inspection. The motor and motor controller should be tuned properly. Teams must submit the power curve and torque curve at the time of technical inspection, along with a motor selection report. Any changes to the motor will lead to disqualification on the spot. The motor should be safely fastened using nut and bolt. It is absolutely forbidden to manipulate the motor. In case of breakdown or malfunction of any internal part, contact the organizer. The motor can be placed near the battery pack or below the battery pack as per the design and ergonomic requirements, and it should be fastened rigidly. The motor and the drive train should be shielded properly. The motor should not be exposed to any of the body parts of the rider.'),
    dict(id='c-046', section='Technical', subsection='Electrical Systems', rule_code='C.10.10',
         title='Motor Controller',
         description='The motor controller is the hardware device that controls the speed and torque of an electric motor. The controller is part of the HVS and can be part of the GLVS. It is allowed to use any type of commercially available controller, and it is allowed to develop the controller or adapt any commercially available device. The hardware components shall be compatible with the working voltage and current values. The controller must comply with all the prescriptions that may apply to it in these technical regulations. The controller must provide over and low voltage protection, over temperature protection, over current protection and brake protection to the motor. The controller voltage should match the voltage of the battery and motor. The controller current rating should be lower than or equal to the continuous current output of the battery. The system should be designed in such a way that all the components are properly tuned with each other.'),
    dict(id='c-047', section='Technical', subsection='Electrical Systems', rule_code='C.10.11',
         title='Drive Train',
         description='Transmission: it is mandatory for the teams to use a rear wheel drive. Any transmission and drive train may be used; either chain, CVT or belt drive can be installed. There is no limitation on the sprocket ratio installed in the bike, and teams are allowed to change the sprocket ratio. Direct transmission between the output shaft of the motor and the rear wheel is allowed. Scatter shield: exposed high-speed final drive train equipment such as sprockets, gears, pulleys, torque converters, clutches, belt/chain drives and clutch drives must be fitted with scatter shields as a failsafe system in the case of failure. The chain cover should be rigidly mounted and the scatter shield must not be hanging from the frame.'),
    dict(id='c-048', section='Technical', subsection='Electrical Connection', rule_code='C.11',
         title='Electrical Connection',
         description='Positioning of the HVS, HVS active lamp, kill switch, throttle, horn, HV fusing, general insulation and wiring, head light, tail light, kinetic energy recovery system and fasteners.'),
    dict(id='c-049', section='Technical', subsection='Electrical Connection', rule_code='C.11.1',
         title='Positioning of the HVS',
         description='All components of the HVS must be located inside a reinforced structure that ensures their integrity in case of a crash.'),
    dict(id='c-050', section='Technical', subsection='Electrical Connection', rule_code='C.11.2',
         title='HVS Active Lamp',
         description='A red warning light that will remain on while the HVS is active shall be installed while the contactor of the battery is closed. It should be installed in such a way that it is visible to the rider in any case.'),
    dict(id='c-051', section='Technical', subsection='Electrical Connection', rule_code='C.11.3',
         title='Kill Switch',
         description='Teams must install two kill switches, both red in colour. One switch must be located so that it is easily accessible to the rider; the other must be at one side of the vehicle and clearly visible from the outside. The kill switches must disconnect all the power sources except the head light and the brake light; the head light and brake light must operate regardless of the kill switch setting. Small stickers indicating "KILL SWITCH" must be attached near the kill switches. The mounting of the kill switches must be rigid.'),
    dict(id='c-052', section='Technical', subsection='Electrical Connection', rule_code='C.11.4',
         title='Throttle',
         description='The throttle installed in the bike must be retractable. It is compulsory to include a throttle potentiometer controlled from the right-side handlebar of the bike; the signal of the potentiometer shall be used to configure the demand of torque or speed from the motor. It is allowed to configure the motor brake with the same potentiometer, mapping it in a range below the acceleration range. The throttle must be covered with a proper grip comfortable enough for the rider\'s actuation. Teams need to submit the report of calculation, selection of material, diameter and safety of throttle.'),
    dict(id='c-053', section='Technical', subsection='Electrical Connection', rule_code='C.11.5',
         title='Horn',
         description='An audible warning must be fitted permanently to the bike. The team must use a 35 W horn in the bike. The team needs to submit the datasheet at the time of the technical inspection. The horn switch should be installed at the left side of the handlebar.'),
    dict(id='c-054', section='Technical', subsection='Electrical Connection', rule_code='C.11.6',
         title='HV Fusing',
         description='The circuit on the HV side must be protected by at least one fuse. Since the battery has very low internal impedance, instantaneous high currents can flow which can seriously damage the battery. Teams should mandatorily use an MCB (mini circuit breaker) which should be instantaneously able to isolate the battery from the other electronic devices to protect the battery from an overload. The current rating of the fuse should be 15% to 20% greater than the current carried through the wire on which it is installed. If several cell strings are mounted in parallel, each of these strings must be protected with its own independent fuse. The fuse holder must be rigidly mounted on the chassis. The tractive system must be appropriately fused.'),
    dict(id='c-055', section='Technical', subsection='Electrical Connection', rule_code='C.11.7',
         title='General Insulation and Wiring',
         description='All conducting wires and connectors must be covered with insulating material, except for direct ground connections. All the electrical wire should be harnessed properly with plastic tubes, spiral rolls and rubber sleeves such that the wires are not exposed. Areas, elements and systems with a high electric risk must be correctly protected against possible contact and manipulations; it is recommended to install rigid insulating housings for a higher protection degree. All conducting wires and connectors must be correctly dimensioned according to the requested current levels. The components of the propulsion system shall be highly protected against humidity; the recommended protection degree is IP-65. The wire length must be exact and rolling of excessive wire lengths is not allowed. The passage of the electric installation through possible hot points must be avoided. The electric installation must be perfectly integrated into the bike assembly. Proper joining methods should be used for wires; simple plastic tapes and insulation tapes are not allowed. Wires should be routed through the chassis or a non-moving member and clamped properly.'),
    dict(id='c-056', section='Technical', subsection='Electrical Connection', rule_code='C.11.8',
         title='Head Light',
         description='The head light should be connected to the auxiliary battery (12 V) or a DC-DC converter. It should be able to glow once the vehicle is turned ON. There should be a separate switch for the head light mounted on the handle. It should be able to operate high beam and low beam light.'),
    dict(id='c-057', section='Technical', subsection='Electrical Connection', rule_code='C.11.9',
         title='Tail Light',
         description='The tail light should be connected to the auxiliary battery (12 V) or a DC-DC converter. It should be able to glow once the vehicle is turned ON. The tail light should turn ON while braking.'),
    dict(id='c-058', section='Technical', subsection='Electrical Connection', rule_code='C.11.10',
         title='Kinetic Energy Recovery System (Optional)',
         description='Energy regeneration is allowed using the motor as a generator during braking. Teams must install the KERS at the rear wheel of the bike. If installed, the KERS data should be represented on the dashboard.'),
    dict(id='c-059', section='Technical', subsection='Electrical Connection', rule_code='C.11.11',
         title='Fasteners',
         description='All threaded fasteners utilized in the driver\'s cell structure, steering, braking and mountings must meet or exceed SAE Grade 5, Metric Grade 8.8 and/or AN/MS specifications. The team must use lock nuts in the wheel assembly, steering mounting, power unit and transmission mounting. It is mandatory to use only metal nuts and bolts for bodywork. Use of any type of plastic or metal tie (such as zip tie, wrap tie, twist tie, wire, etc.) for fixing body parts or components is strictly not allowed.'),
    dict(id='c-060', section='Technical', subsection='Rider Gear', rule_code='C.12',
         title='Rider Gear — General Requirements',
         description='The listed gear are the minimum requirements and restrictions that will be inspected thoroughly at the technical inspection, at any stage of the competition. All parts of the safety gear must meet the required rating specified. No rider is allowed to drive the vehicle without the safety gear in any of the dynamic events. The gear consists of a driver suit, underclothing, helmet, balaclava, neck support, knee and elbow pads, gloves, shoes and socks. Note: no exchange of safety gear is allowed during any dynamic event.'),
    dict(id='c-069', section='Technical', subsection='Rider Gear', rule_code='C.12.1',
         title="Driver's Suit",
         description="A fire-resistant one-piece suit, made from a minimum of 1 layer, that covers the body from the neck down to the ankles and the wrists. The suit must be certified to one of the following standards and be labelled as such: SFI 3.2A/5 (or higher), or FIA Standard 1986."),
    dict(id='c-061', section='Technical', subsection='Rider Gear', rule_code='C.12.2',
         title='Underclothing',
         description='It is strongly recommended that all competitors wear fire-resistant underclothing (long pants and long sleeve t-shirt) under their approved driving suit. The underclothing should be made from an acceptable fire-resistant material and should cover the rider\u2019s body completely from neck down to ankles and wrists. Note: if you do not wear fire-resistant underclothing, it is strongly recommended that you wear cotton underclothing (t-shirt and long underpants) under your approved driving suit.'),
    dict(id='c-062', section='Technical', subsection='Rider Gear', rule_code='C.12.3',
         title='Helmet',
         description='A well-fitting closed-face helmet that meets one of the following certifications and is labelled as such: Snell K2000, K2005, K2010, M2000, M2005, M2010, SA2000, SA2005, SA2010 or DOT; SFI 31.2A or SFI 31.1/2005; FIA 8860-2004 or FIA 8860-2010. Open-faced and motocross helmets are not allowed. All helmets used in the competition must be presented during technical inspection, where approved helmets will be stickered.'),
    dict(id='c-063', section='Technical', subsection='Rider Gear', rule_code='C.12.4',
         title='Balaclava',
         description='A balaclava made from an acceptable fire-resistant material, SFI 3.2A/5 or FIA standard 1986 or higher, covering the rider\u2019s head, hair and neck, or a full helmet skirt of acceptable fire-resistant material. The balaclava requirement applies to riders of either gender, with any hair length.'),
    dict(id='c-064', section='Technical', subsection='Rider Gear', rule_code='C.12.5',
         title='Neck Support',
         description='The neck support must be a full circle (360 degrees) and SFI rated.'),
    dict(id='c-065', section='Technical', subsection='Rider Gear', rule_code='C.12.6',
         title='Knee Pads and Elbow Pads',
         description='Proper knee and elbow pads must be used.'),
    dict(id='c-066', section='Technical', subsection='Rider Gear', rule_code='C.12.7',
         title='Gloves',
         description='Fire-resistant gloves made from acceptable fire-resistant material, SFI / FIA rated. Gloves of all-leather construction, or fire-resistant gloves constructed using leather palms with no insulating fire-resisting material underneath, are not acceptable. Leather gloves with extra foam are acceptable, and teams can use good quality bike gloves.'),
    dict(id='c-067', section='Technical', subsection='Rider Gear', rule_code='C.12.8',
         title='Shoes',
         description='Fire-resistant shoes made from acceptable fire-resistant material. Shoes must be certified to the standard and labelled as such: SFI 3.3, 1.4.8.2, FIA 8856-2000. Note: sport shoes, canvas shoes, leather shoes and industrial safety shoes are not allowed at any point of the event.'),
    dict(id='c-068', section='Technical', subsection='Rider Gear', rule_code='C.12.9',
         title='Socks',
         description='Fire-resistant socks made from acceptable fire-resistant material, which cover the bare skin between the driver\u2019s suit and the boots or shoes.'),

    # ── D. Judging Criteria ────────────────────────────────────────────────────
    dict(id='d-000', section='Judging', subsection='Points Summary', rule_code='D',
         title='Event Points Summary',
         description='Qualifying rounds: Technical Inspection Standard and Driver Safety 0 points; Weight Test 0 points; Brake Test 0 points. Dynamic rounds: Acceleration Test 100; Hill Climb Test 100; Off-Road Test 100; Self-Balancing Test 100; Cross Pad Test 100; Driverless Parking Test 100; Durability Test 300. Static rounds: Design Presentation 100; Business Plan Presentation 50; Cost Report Presentation 50; Innovation Presentation optional. Total 1100 points.'),
    dict(id='d-001', section='Judging', subsection='Qualifying Rounds', rule_code='D.1',
         title='Qualifying Rounds',
         description='Technical Inspection, Weight Test and Brake Test are qualifying rounds. All teams must qualify these rounds to proceed to the dynamic events.'),
    dict(id='d-002', section='Judging', subsection='Qualifying Rounds', rule_code='D.1.1',
         title='Technical Inspection — Documents and Overview',
         description='Each bike will be inspected to determine if it complies with the requirements and restrictions of the rulebook. Each team must bring the following items during technical inspection: insurance documents of the driver, and the approved specification sheet of the electrical system used, with the material certificate certified by the authorized lab. Each bike will be given a maximum of 2 attempts to clear the technical inspection. The bike will be inspected through different segments according to the technical inspection sheet. Presence of the driver and the captain is compulsory during the technical inspection. Technical inspection is a non-scoring activity.'),
    dict(id='d-003', section='Judging', subsection='Qualifying Rounds', rule_code='D.1.1.3',
         title='Technical Inspection — Condition',
         description='The bike must be presented for technical inspection in finished condition, i.e. ready-to-run. Technical inspection will not be done if the bike is brought in an unfinished condition.'),
    dict(id='d-004', section='Judging', subsection='Qualifying Rounds', rule_code='D.1.1.4',
         title='Technical Inspection — Access',
         description='All items on the technical inspection sheet must be clearly visible to the technical inspectors. Visible access may be provided by removing body panels and all other necessary panels.'),
    dict(id='d-005', section='Judging', subsection='Qualifying Rounds', rule_code='D.1.1.5',
         title='Weight Test',
         description='During technical inspection the weight of the vehicle will be checked. The method involves measuring the weight on 2 wheels and adding them together. Note: the weight check is to verify that the vehicle weight is within the rulebook constraints. If a team fails to meet the rules, then for every kilogram beyond the limit a penalty of 2 points will be added to the overall score.'),
    dict(id='d-006', section='Judging', subsection='Qualifying Rounds', rule_code='D.1.2',
         title='Brake Test — Procedure',
         description='The brake test is a qualifying round and each team will be given a maximum of two attempts to qualify. The front tyre of the vehicle will be on the starting line. Upon the flag off, the driver will be asked to accelerate with full throttle until the front tyre reaches the finishing line. The distance between the starting line and the finishing line is 50 m. The vehicle should stop between the finishing line and the dead end line upon actuation of the braking system. The distance between the finishing line and the dead end line is 4 m. Judgment criteria: both tyres of the vehicle must be in locked condition while applying the brakes. If the team fails, they must appear for this round again, with a maximum of 2 attempts.'),
    dict(id='d-007', section='Judging', subsection='Static Rounds', rule_code='D.2',
         title='Static Rounds',
         description='The static rounds evaluate the engineering and business effort behind the vehicle: design presentation, business plan presentation, cost report presentation and an optional innovation presentation.'),
    dict(id='d-008', section='Judging', subsection='Static Rounds', rule_code='D.2.1',
         title='Business Plan Presentation',
         description='Teams are required to present a hypothetical manufacturing plan and how they would put it into mass production, including plans of business setup and marketing. A maximum of 10 slides will be allowed. A time constraint of 10 minutes will be allotted for the business presentation, plus 5 more minutes for a questionnaire from the executives.'),
    dict(id='d-009', section='Judging', subsection='Static Rounds', rule_code='D.2.2',
         title='Cost Report Presentation',
         description='Teams are required to submit their cost report during the submission of reports. The team needs to prepare a presentation including all costs incurred. The cost report format will be mailed by the E-Bike organizing committee.'),
    dict(id='d-010', section='Judging', subsection='Static Rounds', rule_code='D.2.3',
         title='Design Presentation',
         description='The objective of the design round is to evaluate the engineering effort the team went through during the design phase of the vehicle, and how those design parameters meet market requirements and were implemented during manufacture. Judging starts with a design review before the event; the principal document is a design report. Teams will be notified to submit design reports online in PDF format before the event dates, and a hard copy must be presented to the judge during design evaluation. The E-bike must be presented for design judging in finished condition, i.e. fully assembled, complete and ready-to-run.'),
    dict(id='d-011', section='Judging', subsection='Static Rounds', rule_code='D.2.4',
         title='Innovation Presentation (Optional)',
         description='ISIEINDIA strongly believes in smart technology and innovation, so all teams are recommended to develop innovations in their vehicle. In this event, teams are supposed to demonstrate all necessary innovations made to the vehicle. Points for innovations done on the bike will be added to the team total points.'),
    dict(id='d-012', section='Judging', subsection='Dynamic Rounds', rule_code='D.3',
         title='Dynamic Rounds',
         description='The dynamic rounds check acceleration, hill climb, off-road ability, self-balancing, driverless parking, cross-pad maneuverability and durability of the vehicle.'),
    dict(id='d-013', section='Judging', subsection='Dynamic Rounds', rule_code='D.3.1',
         title='Acceleration Test',
         description='The bike needs to accelerate from a standstill over a distance of 50 m on a flat surface. The front part of the vehicle will be positioned behind the starting line, coincident with the starting line, and the time taken to accelerate will be measured. Penalties: a 2-point penalty will be added for each cone knocked down or out, including entry and exit gate cones, on that particular run, to give the corrected elapsed time. If the vehicle did not attempt or did not complete the event, those teams receive DNA (Did Not Attempt).'),
    dict(id='d-014', section='Judging', subsection='Dynamic Rounds', rule_code='D.3.2',
         title='Hill Climb Test',
         description='This round evaluates the gradient-travelling ability of the bike, and judges whether the design considerations made by the team meet the actual vehicle dynamics scenario. A total inclination of 40 degrees will be given, and the time taken to complete the track will be noted. Penalties: if the vehicle hits a cone, 2 seconds will be added per hit; if the cone is totally displaced or falls down, 5 seconds will be added each time.'),
    dict(id='d-015', section='Judging', subsection='Dynamic Rounds', rule_code='D.3.3',
         title='Off-Road Test',
         description='This round checks the off-road ability of the vehicle along with its suspension dynamics on an off-road surface. The vehicle starts from the starting line and travels along the track, traversing all the obstacles in between. Only one attempt will be allotted to every team. Standard speed breakers of 100 mm to a maximum of 140 mm. Mud and water trail will be a maximum of 150-200 mm deep or less. Obstacle course, including the potholes track, will be a maximum of 140 mm deep. Additional obstacles may be present subject to final track preparation at the event. Penalties: if the vehicle stops or gets stuck for more than 10 seconds at any instant, a penalty of 5 seconds is added to the overall time; if stopped for more than 30 seconds, the vehicle is considered to have failed the round.'),
    dict(id='d-016', section='Judging', subsection='Dynamic Rounds', rule_code='D.3.4',
         title='Self-Balancing Run',
         description='This round checks the self-balancing ability of the vehicle on a sharp turning track. The rider must complete the track without using their legs for balancing. The bike must not topple over before completing the circuit, and after completing the track it should be in a standstill condition without any support. During the whole round teams are not allowed to use any side stand, paddock stand, legs or any other support to balance the vehicle. Penalties: if the vehicle hits a cone, 2 seconds will be added per hit; if the cone is totally displaced or falls down, 10 seconds will be added each time.'),
    dict(id='d-017', section='Judging', subsection='Dynamic Rounds', rule_code='D.3.5',
         title='Driverless Parking',
         description='This round checks the driverless parking ability of the vehicle through a voice-controlled or remote-controlled mechanism. Teams need to park the vehicle through voice or remote control. A narrow patch will be provided to park the vehicle. The use of side and paddock stands during this round is prohibited.'),
    dict(id='d-018', section='Judging', subsection='Dynamic Rounds', rule_code='D.3.6',
         title='Cross Pad Test',
         description='This round checks the maneuverability of the bike, to measure its cornering ability on a flat surface while making a constant turn. The track layout will be shared prior to the competition.'),
    dict(id='d-019', section='Judging', subsection='Dynamic Rounds', rule_code='D.3.7',
         title='Durability Test',
         description='In the dynamic round the durability and performance of the vehicle will be checked. Each team must bring a fully drained battery and every team will get 3 hours to charge the batteries, after which teams are required to run the vehicle around 40-50 km in a single charge. Penalties: a 10-point penalty will be added to the durability round if a mechanical breakdown (non-functioning brakes, chain slippage over sprocket, tyre puncture, changes in wheel alignment) is rectified within 5 minutes; failure to rectify within 5 minutes leads to elimination from the endurance round, termed MECHANICAL FAILURE. The same 10-point penalty applies to an electrical breakdown (fusing problem, motor overheating due to excessive load, overheating of accumulator, wire burnout, motor controller issues) rectified within 5 minutes, with elimination after that, termed ELECTRICAL FAILURE. The vehicle will be pulled away from the track if the track marshal directs it, and total laps covered till that time will be counted.'),
    dict(id='d-020', section='Judging', subsection='Dynamic Rounds', rule_code='D.3.7.3',
         title='General Track Penalties',
         description='Over-taking during the formation lap attracts a 5-point penalty. Cone touch, where the vehicle touches a cone placed at the border of the track, attracts a 1-point penalty. Cone down, where the vehicle hits a cone, attracts a 2-point penalty per cone. If any two tyres are found to be out of track, the team faces a penalty of 5 points. If the whole vehicle is out of track, the team faces a penalty of 20 points.'),
    dict(id='d-021', section='Judging', subsection='Command Flags', rule_code='D.4',
         title='Command Flags',
         description='Command flags must be obeyed immediately and without question. Green flag: at a starting line or when re-entering the course, the event has started and you should enter the course under the direction of the starter; when running on the course, the course is clear, proceed. Red flag: there is a dangerous situation somewhere on the track requiring a full-course stop; come to an immediate, safe and controlled stop, passing is not permitted, pull to the side of the track as much as possible and follow course workers. Yellow flag: there is a dangerous situation beyond the flag station; reduce speed and be prepared to take evasive action or stop, and passing is not permitted unless directed by course workers. Black flag furled and pointed: warning that officials are watching this driving, obey the event rules. Black flag displayed: pull into the penalty box for a discussion with the technical inspector or other official concerning an incident, where a penalty may be assessed, or for a mechanical inspection of the vehicle. Chequered flag: the event has been completed; exit the course as directed by event officials.'),
    dict(id='d-022', section='Judging', subsection='Command Flags', rule_code='D.4.6.2',
         title='Directional Arrow',
         description='Orange triangle with a 1.5:1 height-to-base ratio, with or without a forked base. White or black trim is optional. The minimum base width is 6 inches.'),

    # ── E. Awards ──────────────────────────────────────────────────────────────
    dict(id='e-000', section='Awards', subsection='General', rule_code='E',
         title='Awards — Prize Money Summary',
         description='Total prize money is INR 4,50,000. In case the minimum participation is less than 60 teams, the prize money will be revised on a pro-rata basis. Individual awards are tracked as separate items below.'),
    dict(id='e-001', section='Awards', subsection='Prize Money', rule_code='E.1',
         title='Champion',
         description='Award: Champion. Prize: INR 50,000.'),
    dict(id='e-002', section='Awards', subsection='Prize Money', rule_code='E.2',
         title='1st Runner Up',
         description='Award: 1st Runner Up. Prize: INR 30,000.'),
    dict(id='e-003', section='Awards', subsection='Prize Money', rule_code='E.3',
         title='2nd Runner Up',
         description='Award: 2nd Runner Up. Prize: INR 10,000.'),
    dict(id='e-004', section='Awards', subsection='Prize Money', rule_code='E.4',
         title='Best Self Manufactured Vehicle Award',
         description='Award: Best Self Manufactured Vehicle Award. Prize: INR 10,000.'),
    dict(id='e-005', section='Awards', subsection='Prize Money', rule_code='E.5',
         title='Best Durability Test Award',
         description='Award: Best Durability Test Award. Prize: INR 10,000.'),
    dict(id='e-006', section='Awards', subsection='Prize Money', rule_code='E.6',
         title='Runner Up Durability Test Award',
         description='Award: Runner Up Durability Test Award. Prize: INR 5,000.'),
    dict(id='e-007', section='Awards', subsection='Prize Money', rule_code='E.7',
         title='Best Design and Aesthetics Award',
         description='Award: Best Design and Aesthetics Award. Prize: INR 10,000.'),
    dict(id='e-008', section='Awards', subsection='Prize Money', rule_code='E.8',
         title='Best Business Plan & Cost Report',
         description='Award: Best Business Plan & Cost Report. Prize: INR 10,000.'),
    dict(id='e-009', section='Awards', subsection='Prize Money', rule_code='E.9',
         title='Runner Up Business Plan & Cost Report Award',
         description='Award: Runner Up Business Plan & Cost Report Award. Prize: Trophy.'),
    dict(id='e-010', section='Awards', subsection='Prize Money', rule_code='E.10',
         title='Best Innovation Award',
         description='Award: Best Innovation Award. Prize: INR 5,000.'),
    dict(id='e-011', section='Awards', subsection='Prize Money', rule_code='E.11',
         title='Best Acceleration Award',
         description='Award: Best Acceleration Award. Prize: INR 5,000.'),
    dict(id='e-012', section='Awards', subsection='Prize Money', rule_code='E.12',
         title='Best Off-Road Test Award',
         description='Award: Best Off-Road Test Award. Prize: INR 5,000.'),
    dict(id='e-013', section='Awards', subsection='Prize Money', rule_code='E.13',
         title='Runner Up Off-Road Test Award',
         description='Award: Runner Up Off-Road Test Award. Prize: Trophy.'),
    dict(id='e-014', section='Awards', subsection='Prize Money', rule_code='E.14',
         title='Best Hill Climb Test Award',
         description='Award: Best Hill Climb Test Award. Prize: INR 5,000.'),
    dict(id='e-015', section='Awards', subsection='Prize Money', rule_code='E.15',
         title='Runner Up Hill Climb Test Award',
         description='Award: Runner Up Hill Climb Test Award. Prize: Trophy.'),
    dict(id='e-016', section='Awards', subsection='Prize Money', rule_code='E.16',
         title='Best Self Balancing Award',
         description='Award: Best Self Balancing Award. Prize: INR 5,000.'),
    dict(id='e-017', section='Awards', subsection='Prize Money', rule_code='E.17',
         title='Runner Up Self Balancing Award',
         description='Award: Runner Up Self Balancing Award. Prize: Trophy.'),
    dict(id='e-018', section='Awards', subsection='Prize Money', rule_code='E.18',
         title='Best Driverless Parking Award',
         description='Award: Best Driverless Parking Award. Prize: INR 5,000.'),
    dict(id='e-019', section='Awards', subsection='Prize Money', rule_code='E.19',
         title='Runner Up Driverless Parking Award',
         description='Award: Runner Up Driverless Parking Award. Prize: Trophy.'),
    dict(id='e-020', section='Awards', subsection='Prize Money', rule_code='E.20',
         title='Best Cross Pad Test Award',
         description='Award: Best Cross Pad Test Award. Prize: INR 5,000.'),
    dict(id='e-021', section='Awards', subsection='Prize Money', rule_code='E.21',
         title='Runner Up Cross Pad Test Award',
         description='Award: Runner Up Cross Pad Test Award. Prize: Trophy.'),
    dict(id='e-022', section='Awards', subsection='Prize Money', rule_code='E.22',
         title='Lightest Weight Award',
         description='Award: Lightest Weight Award. Prize: INR 5,000.'),
    dict(id='e-023', section='Awards', subsection='Prize Money', rule_code='E.23',
         title='Best Team Work Award',
         description='Award: Best Team Work Award. Prize: INR 5,000.'),
    dict(id='e-024', section='Awards', subsection='Prize Money', rule_code='E.24',
         title='Best Faculty Advisor Award',
         description='Award: Best Faculty Advisor Award. Prize: INR 5,000.'),
    dict(id='e-025', section='Awards', subsection='Prize Money', rule_code='E.25',
         title='Best Women Participant Award',
         description='Award: Best Women Participant Award. Prize: INR 5,000.'),
    dict(id='e-026', section='Awards', subsection='Prize Money', rule_code='E.26',
         title='Future Award',
         description='Award: Future Award. Prize: INR 2,50,000.'),

    # ── F. Rules and Jurisdiction ──────────────────────────────────────────────
    dict(id='f-001', section='Rules and Jurisdiction', subsection='Official Announcement', rule_code='F.1.1',
         title='Official Announcement',
         description='All official announcements and information regarding the competition will be displayed on the official website of Imperial Society of Innovative Engineers: https://imperialsociety.in/. After completion of registration, important information will be sent via email to the respective team email. The rules will be the same throughout the event and any amendments will be informed immediately to all participating teams through mail.'),
    dict(id='f-002', section='Rules and Jurisdiction', subsection='Rules Authority', rule_code='F.1.2',
         title='Rules Authority',
         description='Official announcements from the organizing committee will be considered part of the rules and have the same validity. Queries regarding the meaning or intent of these rules will be resolved by the Participants Relations Manager of the organizing committee.'),
    dict(id='f-003', section='Rules and Jurisdiction', subsection='Rules Authenticity', rule_code='F.1.3',
         title='Rules Authenticity',
         description='The rules and other information related to events are valid till the completion of the event and schedule as decided by the ISIE. Rules of others may be different.'),
    dict(id='f-004', section='Rules and Jurisdiction', subsection='Rules Compliance', rule_code='F.1.4',
         title='Rules Compliance',
         description='By entering through registration in this competition, the team members, team advisors and other personnel of the entering organization agree to comply with and be bound by the rules. All team members, team advisors and other representatives are required to cooperate with, and follow all instructions from competition organizers, officials and judges.'),
    dict(id='f-005', section='Rules and Jurisdiction', subsection='Understanding the Rules', rule_code='F.1.5',
         title='Understanding the Rules',
         description='Teams, team members as individuals and team advisors are responsible for reading and understanding the rules in effect for the competition in which they are participating.'),
    dict(id='f-006', section='Rules and Jurisdiction', subsection='Participating', rule_code='F.1.6',
         title='Participating in the Competition',
         description='Teams, team members as individuals, team advisors and other representatives of a registered organization who are present on-site at a competition are deemed to have accepted the rules by participating.'),
    dict(id='f-007', section='Rules and Jurisdiction', subsection='Right to Impound', rule_code='F.1.7',
         title='The Right to Impound',
         description='During the event, any registered team can be called for technical inspection and examination at any point of time and stage, and can be questioned about any technical element related to the vehicle by any team member.'),
    dict(id='f-008', section='Rules and Jurisdiction', subsection='Restriction of Vehicle Use', rule_code='F.1.8',
         title='Restriction of Vehicle Use',
         description='Teams are cautioned that the vehicles designed by the team are restricted to operate at the event place, and only at the time of the competition.'),
    dict(id='f-009', section='Rules and Jurisdiction', subsection='Behavior', rule_code='F.1.9',
         title='Behavior',
         description='All members of each and every team must follow the rules laid by the organizing committee; failure to follow the rules will result in a 20% point reduction or elimination from the event. Arguments with officials may also result in the team being eliminated. Alcohol, illegal drugs, weapons or other illegal material are strictly not allowed on the event site during the competition. In the event of unsportsmanlike conduct, the team will receive a warning from an official and a second violation will result in expulsion. Failure of a team member to follow an instruction directed specifically to that team or team member will result in a 25 point penalty. Disruptive parties either on or off-site should be prevented by the team advisor. Teams will be responsible for all their tools, equipment and components; ISIE will not be responsible for any kind of loss or damage.'),
    dict(id='f-010', section='Rules and Jurisdiction', subsection='Violation Intent', rule_code='F.1.10',
         title='Violation Intent',
         description='Any violation of this rule by a team member will cause the expulsion of the entire team. This applies to both team members and team advisors. Any use of drugs or alcohol by an underage individual will be reported to the authorities for prosecution.'),
    dict(id='f-011', section='Rules and Jurisdiction', subsection='Competition Objective', rule_code='F.1.11',
         title='Competition Objective — A Reminder',
         description='The SIEP E-Bike Challenge is a competition of design, engineering and manufacturing that requires performance demonstration of an electric bike and is NOT a race. Engineering ethics will apply.'),
]
