# -*- coding: utf-8 -*-
"""Inspection items transcribed from 'TI SHEET.pdf' (SIEP E-Bike Challenge 2025)."""

INSPECTION = [
    # ── PART I — PRE INSPECTION: Driver Details ───────────────────────────────
    dict(id='ti-dd-001', section='Driver Details', item_number='A.1', title='Driver 1 — Name',
         description='Name of Driver 1. An ESO (Electrical Safety Officer) must be present at the inspection.'),
    dict(id='ti-dd-002', section='Driver Details', item_number='A.2', title='Driver 1 — Medical Insurance No',
         description='Medical Insurance number for Driver 1. A copy of the insurance document must be submitted.'),
    dict(id='ti-dd-003', section='Driver Details', item_number='A.3', title="Driver 1 — Driver's College Registration No",
         description="Driver's College Registration number for Driver 1. College ID must be submitted."),
    dict(id='ti-dd-004', section='Driver Details', item_number='A.4', title='Driver 1 — Parent Name',
         description='Parent name of Driver 1.'),
    dict(id='ti-dd-005', section='Driver Details', item_number='A.5', title='Driver 1 — Blood Group',
         description='Blood group of Driver 1.'),
    dict(id='ti-dd-006', section='Driver Details', item_number='A.6', title='Driver 1 — Driving License No',
         description='Valid driving licence number for Driver 1. A copy of the driving licence must be submitted.'),
    dict(id='ti-dd-007', section='Driver Details', item_number='A.7', title='Driver 1 — Indemnity Form No',
         description='Indemnity form number for Driver 1.'),
    dict(id='ti-dd-008', section='Driver Details', item_number='A.8', title='Driver 1 — Date of Birth (DOB)',
         description='Date of birth of Driver 1.'),
    dict(id='ti-dd-009', section='Driver Details', item_number='A.9', title='Driver 1 — Contact No',
         description='Contact number of Driver 1.'),
    dict(id='ti-dd-010', section='Driver Details', item_number='A.10', title='Driver 2 (If Any) — Full Details',
         description='If a second driver is participating, the same set of details must be recorded: name, medical insurance no, college registration no, parent name, blood group, driving licence no, indemnity form no, date of birth and contact no.'),
    dict(id='ti-dd-011', section='Driver Details', item_number='A.11', title='Driver Documents Submitted',
         description='A copy of the following documents must be submitted for both drivers: driving licence, medical and accidental insurance, Aadhaar card and college ID.'),
    dict(id='ti-dd-012', section='Driver Details', item_number='A.12', title='Driver Change Policy Acknowledged',
         description='Note: once the driver is approved by the Technical Inspector, a driver change will not be allowed in any case.'),

    # ── PART I — Driver Gear and Safety ────────────────────────────────────────
    dict(id='ti-dg-001', section='Driver Gear and Safety', item_number='1', title="Driver's Suit",
         description="Fire-resistant one-piece suit made from a minimum of 1 layer that covers the body from the neck down to the ankles and the wrists. Slack rating: SFI 3.2A/5 (or higher) / FIA Standard 1986."),
    dict(id='ti-dg-002', section='Driver Gear and Safety', item_number='2', title='Underclothing',
         description='Fire-resistant underclothing made from an acceptable fire-resistant material that should cover the driver\'s body completely from neck down to ankles and also the wrists.'),
    dict(id='ti-dg-003', section='Driver Gear and Safety', item_number='3', title='Helmet',
         description='A well-fitting closed-face helmet that meets one of the following certifications and is labelled as such: Snell K2000, K2005, K2010, M2000, M2005, M2010, SA2000, SA2005, SA2010 or DOT; SFI 31.2A or SFI 31.1/2005; FIA 8860-2004 or FIA 8860-2010. Open-faced and motocross helmets are not permissible. All helmets must be presented during technical inspection, where approved helmets will be stickered.'),
    dict(id='ti-dg-004', section='Driver Gear and Safety', item_number='4', title='Balaclava',
         description='A balaclava which covers the driver\'s head, hair and neck, made from an acceptable fire-resistant material (SFI 3.2A/5 or FIA standard 1986 or higher), or a full helmet skirt of acceptable fire-resistant material.'),
    dict(id='ti-dg-005', section='Driver Gear and Safety', item_number='5', title='Neck Support',
         description='The neck support must be a full circle (360°) and SFI rated.'),
    dict(id='ti-dg-006', section='Driver Gear and Safety', item_number='6', title='Gloves',
         description='Fire-resistant gloves made from acceptable fire-resistant material (SFI / FIA rated). Gloves of all-leather construction, or fire-resistant gloves with leather palms and no insulating fire-resisting material underneath, are not acceptable. Leather gloves with extra foam are acceptable.'),
    dict(id='ti-dg-007', section='Driver Gear and Safety', item_number='7', title='Shoes',
         description='Fire-resistant shoes made from acceptable fire-resistant material. Shoes must be certified to the standard and labelled as such: SFI 3.3, 1.4.8.2, FIA 8856-2000. Sport shoes, canvas shoes, leather shoes and industrial safety shoes are not allowed at any point of the event.'),
    dict(id='ti-dg-008', section='Driver Gear and Safety', item_number='8', title='Socks',
         description='Fire-resistant socks made from acceptable fire-resistant material, which cover the bare skin between the driver\'s suit and the boots or shoes.'),
    dict(id='ti-dg-009', section='Driver Gear and Safety', item_number='9', title='Knee Pads and Elbow Pads',
         description='Proper knee and elbow pads must be used.'),
    dict(id='ti-dg-010', section='Driver Gear and Safety', item_number='10', title='First Aid Box',
         description='The team must carry a first aid box.'),
    dict(id='ti-dg-011', section='Driver Gear and Safety', item_number='11', title='Goggles',
         description='The driver must wear goggles.'),
    dict(id='ti-dg-012', section='Driver Gear and Safety', item_number='12', title='Fire Extinguisher',
         description='The team must have at least two dry chemical / dry powder fire extinguishers with a minimum firefighting agent capacity of 0.9 kg.'),

    # ── PART II — Electrical Inspection ────────────────────────────────────────
    dict(id='ti-el-001', section='Electrical Inspection', item_number='13', title='Rules and Definitions — ESO Present',
         description='An ESO (Electrical Safety Officer) must be present at the inspection.'),
    dict(id='ti-el-002', section='Electrical Inspection', item_number='14', title='High Voltage System',
         description='Any circuit with a potential difference above 40 VDC will be part of the High Voltage (HV) system of the bike; below this voltage it is part of the Low Voltage (LV) system. The maximum permitted voltage of the HV system shall be 72 VDC. The use of software elements to control the maximum voltage is allowed. HV cables must be shielded. The HVS must be electrically separated from the bike chassis or ground. There must be high voltage labels such as "HIGH VOLTAGE". The HVS must have a controller device fitted in between the motor and the battery. The dashboard must be fitted with a display showing the voltage between terminals in the HVS at any given time. Check: the corresponding value of the real HVS voltage and the value shown on the dashboard. All components of the HVS must be located inside a reinforced structure that ensures their integrity in case of a crash.'),
    dict(id='ti-el-003', section='Electrical Inspection', item_number='15', title='Wiring and Insulation',
         description='The HVS and the GLVS shall be galvanically separated. All components of the HVS must be insulated and protected against direct contact. The HVS connections must be encapsulated in insulating components. The cables or conductors pertaining to the HVS must be orange, or clearly marked with orange, and non-flammable grade UL-94 V0, FAR 25 or equivalent. All the electrical wire should be harnessed properly with plastic tubes, spiral rolls and rubber sleeves such that the wires are not exposed. All conducting wires and connectors must be covered with insulating material, except for direct ground connections. Areas, elements and systems with a high electric risk must be correctly protected against possible contact and manipulations. All conducting wires and connectors must be correctly dimensioned according to the requested current levels. The components of the propulsion system shall be highly protected against humidity; the recommended protection degree is IP-65. The wire length must be exact; excessive wire lengths with rolling are not allowed. The passage of the electric installation through possible hot points must be avoided and the electric installation must be perfectly integrated into the bike assembly. Proper joining methods should be used for wires; simple plastic tapes and insulation tapes are not allowed. Wires should be routed through the chassis or a non-moving member and clamped properly.'),
    dict(id='ti-el-004', section='Electrical Inspection', item_number='16', title='HV Fusing',
         description='The circuit on the HV side must be protected by at least one fuse. Use of an MCB (mini circuit breaker) which should be instantaneously able to isolate the battery from the other electronic devices to protect the battery from an overload. The current rating of the fuse should be greater (15% to 20%) than the current carried through the wire on which it is installed. If several cell strings are mounted in parallel, each of these strings must be protected with its own independent fuse. The fuse holder must be rigidly mounted on the chassis. The tractive system must be appropriately fused.'),
    dict(id='ti-el-005', section='Electrical Inspection', item_number='17', title='Battery Pack Specification',
         description='Teams are allowed to use a pre-manufactured battery pack available in the market and a self-manufactured or assembled battery pack. Li-Ion battery only. The battery pack should be IEC 60529 IP67 certified. Allowed nominal voltage: 48 V to 72 V. Allowed energy: minimum 1.5 kWh, maximum 2.5 kWh. Battery health certificate required.'),
    dict(id='ti-el-006', section='Electrical Inspection', item_number='18', title='Battery Safety',
         description='If the power storage pack is capable of spilling dangerous liquids when damaged, there must be a spill-proof barrier between that storage pack and the bike occupants. If it is capable of emitting dangerous gases when damaged, there must be a proper ventilation system designed. The battery pack must have proper short circuit protection. Teams should use good quality working mini circuit breakers (MCB) for protecting it from high loads. The current rating of the MCB should be equal to or greater than the motor controller rating. All safety devices like the brake light, indicator lights and horn should be powered either by the auxiliary battery (12 V) or a DC-DC converter. None of the battery parts or wires should be exposed to any body part of the rider.'),
    dict(id='ti-el-007', section='Electrical Inspection', item_number='19', title='Battery Level Indicator',
         description='The battery pack must contain a temperature sensor whose reading must be accurately indicated on the dashboard. It should display the percentage or bar of the battery based on the voltage or current of the battery pack for the full time during the event. The battery pack may contain a smoke sensor whose reading must be accurately indicated on the dashboard.'),
    dict(id='ti-el-008', section='Electrical Inspection', item_number='20', title='Battery Management System (BMS)',
         description='The installation of a battery management system (BMS) is compulsory. The BMS must provide full cell protection to cover almost any eventuality and must read the voltage of each cell in order to keep the cells within the voltage limits established by the manufacturer. The BMS must deactivate the vehicle traction if the voltage of one of the cells is discharged to the critical minimum voltage, or if the critical maximum temperature of the cell is exceeded. The BMS must provide over-charge and over-discharge protection while charging and discharging, over-current protection, over-temperature and under-temperature protection, short circuit protection, reverse polarity protection and cell balancing functions. The BMS must also deactivate the recharge system when the maximum voltage or temperature levels of the cell are reached.'),
    dict(id='ti-el-009', section='Electrical Inspection', item_number='21', title='Motor Power Rating',
         description='Teams are allowed to use any type of motor, AC or DC, and it should vary from 1250 W to 2000 W rated power. The motor and motor controller should be tuned properly. The motor should be safely fastened, and the motor and drive train should be shielded properly. The motor should not be exposed to any of the body parts of the rider. The motor can be placed near the battery pack or below the battery pack. Teams must submit the power curve, torque curve and motor selection report.'),
    dict(id='ti-el-010', section='Electrical Inspection', item_number='22', title='Motor Controller',
         description='It is allowed to use any type of commercially available controller. The controller must provide over and low voltage protection, over temperature protection, over current protection and brake protection to the motor. The controller voltage should match the voltage of the battery and motor. The controller current rating should be lower than or equal to the continuous current output of the battery. The system should be designed in such a way that all the components are properly tuned with each other.'),
    dict(id='ti-el-011', section='Electrical Inspection', item_number='23', title='HVS Active Lamp',
         description='A red warning light that will remain on while the HVS is active shall be installed while the contactor of the battery is closed. It should be installed in such a way that it is visible to the rider in any case.'),
    dict(id='ti-el-012', section='Electrical Inspection', item_number='24', title='Kill Switch',
         description='Two kill switches, red in colour. The kill switches must disconnect all the power sources except the head light and the brake light. The kill switches must be mounted rigidly. Small stickers indicating "KILL SWITCH" must be attached near the kill switches. One must be installed at the dashboard and one at the side of the bike.'),
    dict(id='ti-el-013', section='Electrical Inspection', item_number='25', title='Throttle',
         description='The throttle installed in the bike must be retractable. It is compulsory to include a throttle potentiometer which is controlled from the right-side handlebar of the bike. The signal of the potentiometer shall be used to configure the demand of torque or speed from the motor. The throttle must be covered with a proper grip comfortable enough for the rider\'s actuation.'),
    dict(id='ti-el-014', section='Electrical Inspection', item_number='26', title='Horn',
         description='The team must use a 35 W horn in the bike. The horn switch should be installed at the left side of the handlebar.'),
    dict(id='ti-el-015', section='Electrical Inspection', item_number='27', title='Head Light',
         description='The head light should be connected to the auxiliary battery (12 V) or a DC-DC converter. It should be able to glow once the vehicle is turned ON. There should be a separate switch for the head light mounted on the handle. It should be able to operate high beam and low beam light.'),
    dict(id='ti-el-016', section='Electrical Inspection', item_number='28', title='Tail Light',
         description='The tail light should be connected to the auxiliary battery (12 V) or a DC-DC converter. It should be able to glow once the vehicle is turned ON. The tail light should turn ON while braking.'),
    dict(id='ti-el-017', section='Electrical Inspection', item_number='29', title='Kinetic Energy Recovery System',
         description='Energy regeneration is allowed using the motor as a generator during braking. Teams must install the KERS at the rear wheel of the bike. If installed, the KERS data should be represented on the dashboard.'),

    # ── PART III — Mechanical Inspection ───────────────────────────────────────
    dict(id='ti-me-001', section='Mechanical Inspection', item_number='30', title='Vehicle Dimension',
         description='The wheelbase of the bike should be in the range of 48 inches to 62 inches. The minimum ground clearance should be 5 inches. The maximum length, width and height should not exceed more than 80 inches, 40 inches and 60 inches. All parts of the bike including the driver should lie within the end to end points of the handle.'),
    dict(id='ti-me-002', section='Mechanical Inspection', item_number='31', title='Wheels',
         description='The minimum diameter of the tires should be 16 inches. The maximum allowed tire width is 7 inches. Bicycle tires and Moto GP slick tires are prohibited.'),
    dict(id='ti-me-003', section='Mechanical Inspection', item_number='32', title='Paddock Stand',
         description='The maximum height of the paddock stand should be 78 cm. The maximum length of the paddock stand should be 50 cm. The maximum width of the paddock stand should be 54 cm. There must be side stands and no main stand.'),
    dict(id='ti-me-004', section='Mechanical Inspection', item_number='33', title='Chassis Cross Section',
         description='A double cradle frame should consist of two main pipes. Minimum wall thickness must be 1 mm. One end of the chassis must be open to check the material. All welding points in the frame should be intact; damaged frames will be disqualified on spot.'),
    dict(id='ti-me-005', section='Mechanical Inspection', item_number='34', title='Material Specification',
         description='Steel / aluminum / carbon fibre. In the case of steel, the minimum carbon percentage should be 0.1%. Material composition and strength test certificate from a certified laboratory only (NABL accredited lab).'),
    dict(id='ti-me-006', section='Mechanical Inspection', item_number='35', title='Mudguard',
         description='The use of front and rear mudguards is compulsory.'),
    dict(id='ti-me-007', section='Mechanical Inspection', item_number='36', title='Suspension System',
         description='Teams are allowed to use a pre-fabricated suspension system of any bike at the front as well as at the rear. If teams customize the suspension system, they must submit the entire suspension design report and all calculations including the CAD model and dynamic simulation. Teams are allowed to use either mono-shock or twin shock suspension at the rear.'),
    dict(id='ti-me-008', section='Mechanical Inspection', item_number='37', title='Steering System',
         description='Teams are allowed to use a pre-fabricated bike handle; if any modification is made, the design report including its methodology must be checked. The turning angle must be limited with positive stoppers on both sides. These stoppers should be made of nylon, aluminum or materials of similar hardness. Neither the chassis, nor any other part of the prototype may act as a steering stopper. The minimum turning angle of the steering must be 150 degrees measured on either side of the longitudinal axis of the prototype. The allowed rake angle is 22 to 32 degrees. Steering axis inclination should have offset with the front wheel center.'),
    dict(id='ti-me-009', section='Mechanical Inspection', item_number='38', title='Braking System',
         description='Hydraulic disc brakes with two independent hydraulic circuits. Components not prone to failure are: a brake pedal and its bearing, and the brake lever. The front and the rear must have different disc diameters. Ventilated discs are prohibited. The front brake pedal should be of lever type and hand operated. The rear brake pedal should be mounted near the foot rest and foot operated. The lever and pedal must be rigidly mounted. The bike must have red colored brake lights at the rear, visible from a distance of 30 m; LED light strips are not allowed to be used as a brake light. The brake light should also function even when the motor is killed off and must glow continuously when brakes are applied.'),
    dict(id='ti-me-010', section='Mechanical Inspection', item_number='39', title='Dashboard',
         description='The dashboard must be behind the vertical plane drawn from the head light. The bike must have at least a standard dashboard displaying speed, battery level indicator (in % or bar), battery temperature, turn indicators, and high beam and low beam headlight indicators. A smart dashboard may additionally show a smoke detection indicator; teams are allowed to use a tablet, mobile or any other digital integrated dashboard connected to an external device through an application. The dashboard should not exceed beyond the head light. Maximum dimensions: length 10 inch, width 7 inch. The dashboard must be fixed, have protective covering from dust and water, be visible and accessible to the rider, and be rigidly mounted.'),
    dict(id='ti-me-011', section='Mechanical Inspection', item_number='40', title='Battery Casing',
         description='There should be a separate battery pack container and battery pack casing enclosures. The battery pack casing should be made of rigid plastic, glass fiber or sheet metal with an insulating coating. The cover material of the battery pack must be fire and electric proof and properly insulated. Flexible rubber or plastic sheets are not allowed to be used as covers. The battery pack container should be fixed, welded or fastened using lock nuts to the chassis. A forced convection cooling system is permitted. Liquid cooling of the battery pack is prohibited. The battery pack with casing must be installed inside the container for easy removal.'),
    dict(id='ti-me-012', section='Mechanical Inspection', item_number='41', title='Battery Position',
         description='Self-manufactured class: the battery must be inserted from the top. Zip tags are prohibited; use the wire coverings and attach them along the frame. It must be mounted rigidly, and nylon ties, strings or wires of any kind are not allowed for mounting. Retrofitting class: the battery may be placed below the existing battery, just above or adjacent to the motor, without removing the frame backbone.'),
    dict(id='ti-me-013', section='Mechanical Inspection', item_number='42', title='Battery Charging Mount and Swapping',
         description='Teams must have a single point accessible charging point on the bike for charging the batteries at either side of the bike. Teams should have a charging connector as per the charger specifications, and must submit the charger and charging connector datasheet at the time of technical inspection. The battery pack must be mounted so it can be swapped at any time from the top in the Self-Manufactured class and from the side in the Retrofit class. The swapping area must be indicated with a yellow sticker near the swapping area. Swapping should be clean and safe with easy removal of the battery from the container.'),
    dict(id='ti-me-014', section='Mechanical Inspection', item_number='43', title='Transmission',
         description='Rear wheel drive only. Any transmission and drive train may be used; direct transmission between the output shaft of the motor and the rear wheel is allowed.'),
    dict(id='ti-me-015', section='Mechanical Inspection', item_number='44', title='Scatter Shield',
         description='Exposed high-speed final drive train equipment such as sprockets, gears, pulleys, torque converters, clutches, belt/chain drives and clutch drives must be fitted with scatter shields. The chain cover should be rigidly mounted. The scatter shield must not be hanging from the frame.'),
    dict(id='ti-me-016', section='Mechanical Inspection', item_number='45', title='Fasteners',
         description='All threaded fasteners utilized in the driver\'s cell structure, steering, braking and mountings must meet or exceed SAE Grade 5, Metric Grade 8.8 and/or AN/MS specifications. The team must use lock nuts in the wheel assembly, steering mounting, power unit and transmission mounting. It is mandatory to use only metal nuts and bolts for bodywork. Use of any type of plastic or metal tie (such as zip tie, wrap tie, twist tie, wire, etc.) for fixing body parts or components is strictly not allowed.'),

    # ── PART IV — Brake Test ───────────────────────────────────────────────────
    dict(id='ti-bt-001', section='Brake Test', item_number='BT.1', title='Track Layout Verified',
         description='Qualifying round, maximum 2 attempts. The front tyre of the vehicle is on the starting line; on the flag off, accelerate at full throttle until the front tyre reaches the finishing line. The distance between the starting line and the finishing line is 50 m, and the distance between the finishing line and the dead end line is 4 m. The vehicle must stop between the finishing line and the dead end line on actuation of the braking system.'),
    dict(id='ti-bt-002', section='Brake Test', item_number='BT.2', title='Vehicle Yaw / Drift Within Limit',
         description='Vehicle yawing or drifting more than 30 degrees is not acceptable.'),
    dict(id='ti-bt-003', section='Brake Test', item_number='BT.3', title='Wheels Lock on Braking',
         description='Judgment criteria: both tyres of the vehicle must be in the locked condition while applying the brakes. If the team fails, they must appear for this round again, with a maximum of 2 attempts.'),
    dict(id='ti-bt-004', section='Brake Test', item_number='BT.4', title='Track Covered Within Time',
         description='The track should be covered within 10 seconds.'),
    dict(id='ti-bt-005', section='Brake Test', item_number='BT.5', title='Brake Light Functions',
         description='The brake light must glow continuously when brakes are applied and should also function even when the motor is killed off.'),

    # ── Approval / Final Inspection ───────────────────────────────────────────
    dict(id='ti-ap-001', section='Approval / Final Inspection', item_number='AP.1', title='All Previous Sections Approved',
         description='Driver details, driver gear and safety, electrical inspection, mechanical inspection and brake test must all be approved before final sign-off.'),
    dict(id='ti-ap-002', section='Approval / Final Inspection', item_number='AP.2', title='TI Sticker Affixed',
         description='The vehicle will be marked with a sticker if it has passed the technical inspection successfully. The technical board will retain this form to certify at any time that the vehicle has the original components that it went through technical inspection with.'),
    dict(id='ti-ap-003', section='Approval / Final Inspection', item_number='AP.3', title='Inspector Names Recorded',
         description='Inspector names must be recorded in the approval block for each part of the inspection sheet.'),
    dict(id='ti-ap-004', section='Approval / Final Inspection', item_number='AP.4', title='Date, Time and Signature when Passed',
         description='Date, time and the inspector signature must be recorded in the approval block for each part of the inspection sheet.'),
]
